### ISSUE TITLE
Node attibutes

### ISSUE THREAD

**Issue by celinescornavacca** [igel-kun/phylo_tools#1]
To code my tools, I need the nodes of our trees and networks to have several attributes: distance to father, bootstrap values. Also the newich reader needs to be modified to extract this information from the network string.

**Comment by igel-kun** [comment]
As part of a major overhaul, restructurization and readability-increase, I also added support for attaching any data to a node. To this end, you'll have to use `TreeNodeWithData` or `NetworkNodeWithData`. I also added an example for how to use those :)

For the second point: the newick parser should already read branchlengths. To this end, simply call `read_tree()` with a `WEdgeList` or `WEdgeVec` as parameter (those store edges along with a float indicating their length). The constructors of `TreeT` and `NetworkT` do not take edge lengths into account, so for trees, the lengths can be added to the nodes after construction (just like the example I added), but for networks I might have to change the `NetworkT` data structure.... hmm hmm, I'll think of something :)

**Comment by igel-kun** [comment]
okay, so  attaching data to edges prompted a major change in the intestines of the network data structure, which is now done. I added an example to demonstrate handling branch lengths. I think I managed to hide most of the template madness that is going on in the background and provided some nice ways of iterating over in/out-edges and parents/children. Feel free to browse and/or ask about the new structure :)

**Comment by igel-kun** [comment]
sorry, playing with github ^^

**Comment by igel-kun** [comment]
this is working correctly in the new C++ branch by the way :)

**Comment by igel-kun** [comment]
Oh sorry forgot to explain how to use the newick reader to extract that data:
To do this, you have 2 options:

1. (recommended) write a single `struct` containing all your node-data (and one for your edge-data) and write a constructor for that `struct` that takes a `const std::string_view`. The parser will automatically pass the string containing the node-data (edge-data) read in the newick file to the constructor.
2. parse your newick via `Phylo N = parse_newick(in, create_node, create_adjacency)` where
(a) `create_node` is a function/lambda/functor taking a `const std::string_view` and returning a `NodeDesc` (usually forwarded from the network's `create_node` function) (**IMPORTANT**: the `NodeDesc` must describe a node of the network (`typename Phylo::Node`)) and
(b) `create_adjacency` is a function/lambda/functor taking a `NodeDesc u` and a `const std::string_view` and returning an adjacency of the network (`typename Phylo::Adjacency`) (**IMPORTANT**: this adjacency must point towards `u`)

If you insist on using method 2, here's an example assuming that your node data has a method `from_string` taking a `std::string_view` and you have a function `str2edge_data` converting a `std::string_view` to your edge data:
```lang-c++
using Adjacency = typename Phylo::Adjacency;

Phylo N = parse_newick(in, 
         [](const std::string_view s){
               const NodeDesc result = Phylo::create_node();
               Phylo::node_of(result).data().from_string(s);
               return result;
         },
         [](const std::string_view s){
               return Adjacency(u, str2edge_data(s));
         }
        );
```
